    // TODO:
    //
    // Generate all selectors automatically during build based on named HTML structures
    //
    var selectors = {
        homePage: '[page="home"]',
        searchPage: '[page="search"]',
        listViewContainer: '[listview-clone]',
        searchContainer: '[search-clone]',
        buttonContainer: '[button-clone]',
        problemsListContainer: '[problems-clone]',
        problemsListCloneable: '[cloneable][name="problemsList"]',
        searchBoxCloneable: '[cloneable][name="searchBox"]',
        searchButtonCloneable: '[cloneable][name="searchButton"]',
        searchBox:  '[name="outerBox"]',
        searchTitle: '[name="title"]',
        searchButton: '[name="search"]',
        inputBox: '[name="inputBox"]',
        suggestions: '[name="suggestions"]',
        suggestionItems: '[name="suggestions"] div',
        listViewCloneable: '[cloneable][name="listView"]',
        listViewListItemRepeatable: '[repeatable][name="listItem"]',
        listViewNumResults: '[name="numResults"]',
        ProblemsListItemRepeatable: '[repeatable][name="listItem"]',
        ProblemsListText: '[name="text"]',
        ProblemsListTimestamp: '[name="timestamp"]',
        ProblemsListGauge: '[name="gauge"]',
        ProblemsListBars: '[name="bars"]',
        MoreOrLessInfo: '[name="moreOrLessInfo"]',
        ListItemOverflow: '[name="listItemOverflow"]',
        ItemName: '[name="itemName"]',
        metricDate: '[name="metricDate"]',
        listViewExtendedInfoRepeatable: '[repeatable][name="extendedInfo"]',
        Item1: '[name="i1"]',
        Item1Value: '[name="i1_value"]',
        Item2: '[name="i2"]',
        Item2Value: '[name="i2_value"]',
        Item3: '[name="i3"]',
        Item3Value: '[name="i3_value"]',
        Item3Trend: '[name="i3_trend"]',
        Item4: '[name="i4"]',
        Item4Value: '[name="i4_value"]',
        Item4Trend: '[name="i4_trend"]',
        listViewChartRepeatable: '[repeatable][name="chart"]',
        chartWidgetContainer: '[name="chartWidgetContainer"]',
        listViewSubchartRepeatable: '[repeatable][name="subchart"]',
        chartThing: '[name="chartThing"]'
    }